name: CloudMusic-LevelUp
on:
  schedule:
    - cron: '1 */2 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-secriy-CloudMusic
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync secriy-CloudMusic
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/secriy/CloudMusic-LevelUp.git"
          source_branch: "master"
          destination_branch: "CloudMusic-LevelUp"
          github_token: ${{ secrets.PAT }}
